apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-qa
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage
  hostPath:
    path: /data/shared-qa
    type: DirectoryOrCreate
